language: node_js
node_js:
- 6
deploy:
  provider: npm
  email: sliv.code@gmail.com
  api_key:
    secure: H1pk7iYezuRCQw2F6GV8whIVEeQsG5k2BJC8/tsSgyVPDoRcFsRlQBHFx2gk3aDEUrNemlR56XAEw7nviezAEACWuAtmugH8Eva3NvrQpq0TYE/YgPD3MJnLvW59ngDLePwhTG9Y2iYV8X/guDLGVHrXiKMJfeRJCl22CCBHOprTR8a0ecMhdkYY42OZeaN8v3Db3IvSdJ9J9C5ru3Wx9Km7fYR1ZzH9umGmOcmy01hTaQUATSvKg4Rgd6RHIAvPMwPY6eWC2yt+mQ96wYuw0Uu9FVQOWDku2S+f5ea3szBrHEuwRonaKd5/P4kDoqyGlojEQv1PPg/OOn/+/uqgdqPhqtQ4Z3VmZliW6r6Deyh0+OeTQhO3AL51eZ2cZz0qKAGjEIaUlOeZhvfbaUwjvwiMtRp9dM0MzKRZfat2QtzTucXIuq2xsbLhmRN+QPlxGS6PYs+d6y5m9gP57jVHPaR+HBywSYOa7TNfkgzYbrL/uAOMc8v4VZJLTi4s574jTQvdGgO6JP7H9KJ/Fy1ixy8tGgGTkVgbKYYnF+bmWUuMIQjQkuODFv8enyALJnoUpKnYmjfhgwnL1dPe7r40tKHrR8nOjO/lQ03czyvHzqk88dpXQtlMVdOTT8AIQey0ijcWXtV+q8zRgU2GbHZKOMtrC9rcZBTGCxgnSx1Pyns=
  on:
    tags: true
    repo: slivcode/ramda-match
